"""
Django settings for pdxheo project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from machina import get_apps as get_machina_apps


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$)*mhm-tzs@)xesra_1$*n2ty99-0w*6=^q3v8p-k)rn71o&^o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
  'django.contrib.admin',
  'django.contrib.auth',
  'django.contrib.contenttypes',
  'django.contrib.sessions',
  'django.contrib.messages',
  'django.contrib.staticfiles',
  'website.apps.WebsiteConfig',
  'rest_framework',

  #machina related apps:
  'mptt',
  'haystack',
  'widget_tweaks',
] + get_machina_apps()

MIDDLEWARE = [
  'django.middleware.security.SecurityMiddleware',
  'django.contrib.sessions.middleware.SessionMiddleware',
  'django.middleware.common.CommonMiddleware',
  'django.middleware.csrf.CsrfViewMiddleware',
  'django.contrib.auth.middleware.AuthenticationMiddleware',
  'django.contrib.messages.middleware.MessageMiddleware',
  'django.middleware.clickjacking.XFrameOptionsMiddleware',
     # Machina
  'machina.apps.forum_permission.middleware.ForumPermissionMiddleware',
]

HAYSTACK_CONNECTIONS = {
  'default': {
    'ENGINE': 'haystack.backends.simple_backend.SimpleEngine',
  },
}

ROOT_URLCONF = 'pdxheo.urls'

# from machina import MACHINA_MAIN_TEMPLATE_DIR
# TEMPLATES = [
#   {
#     'BACKEND': 'django.template.backends.django.DjangoTemplates',
#     'DIRS':( [os.path.join(BASE_DIR, 'templates')],
#         MACHINA_MAIN_TEMPLATE_DIR,
#     ),
#    # 'APP_DIRS': True,
#     'OPTIONS': {
#       'context_processors': [
#         'django.template.context_processors.debug',
#         'django.template.context_processors.request',
#         'django.contrib.auth.context_processors.auth',
#         'django.contrib.messages.context_processors.messages',
#
#         #machina
#         'machina.core.context_processors.metadata',
#       ],
#     },
#   },
# ]

#TODO: fix template error - follow https://django-machina.readthedocs.io/en/stable/getting_started.html#requirements
from machina import MACHINA_MAIN_TEMPLATE_DIR
TEMPLATES = [
  {
    'BACKEND': 'django.template.backends.django.DjangoTemplates',
    'DIRS': (
      os.path.join(BASE_DIR, 'templates'),
      MACHINA_MAIN_TEMPLATE_DIR,
    ),
    'OPTIONS': {
      'context_processors': [
        # ...
        'django.template.context_processors.debug',
        'django.template.context_processors.request',
        'django.contrib.auth.context_processors.auth',
        'django.contrib.messages.context_processors.messages',
        # Machina
        'machina.core.context_processors.metadata',
      ],
      'loaders': [
          'django.template.loaders.filesystem.Loader',
          'django.template.loaders.app_directories.Loader',
      ]
    },
  },
]

# TEMPLATES = [
#   {
#     'BACKEND': 'django.template.backends.django.DjangoTemplates',
#     'DIRS': [os.path.join(BASE_DIR, 'templates')]
#     ,
#     'APP_DIRS': True,
#     'OPTIONS': {
#       'context_processors': [
#         'django.template.context_processors.debug',
#         'django.template.context_processors.request',
#         'django.contrib.auth.context_processors.auth',
#         'django.contrib.messages.context_processors.messages',
#       ],
#     },
#   },
# ]

from machina import MACHINA_MAIN_STATIC_DIR
STATICFILES_DIRS = (
  # ...
  MACHINA_MAIN_STATIC_DIR,
)

CACHES = {
  'default': {
    'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
  },
  'machina_attachments': {
    'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
    'LOCATION': '/tmp',
  }
}

WSGI_APPLICATION = 'pdxheo.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# TODO: NOT SECURE!
if os.getenv('SERVER_SOFTWARE', '').startswith('Google App Engine'):
  DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.postgresql_psycopg2',
      'HOST': '/cloudsql/pdx-heo:us-west1:pdx-heo-postgresql',
      'NAME': 'pdxheo',
      'USER': 'pdxheo',
      'PASSWORD': 'password',
    }
  }
else:
  DATABASES = {
    'default': {
      'ENGINE': 'django.db.backends.postgresql_psycopg2',
      'NAME': 'pdxheo',
      'USER': 'pdxheo',
      'PASSWORD': 'password',
      'HOST': '35.197.30.92',
      'PORT': '',
    }
  }

REST_FRAMEWORK = {
    'PAGE_SIZE': 10
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
  {
    'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
  {
    'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
  },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_REDIRECT_URL = 'index'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
