# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('hours_open', models.TimeField(verbose_name='open time')),
                ('hours_close', models.TimeField(verbose_name='close time')),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
                ('hours_open', models.TimeField(verbose_name='open time')),
                ('hours_close', models.TimeField(verbose_name='close time')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Organization')),
            ],
        ),
    ]
