# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-06 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
