# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('hours_open', models.TimeField(blank=True, null=True, verbose_name='open time')),
                ('hours_close', models.TimeField(blank=True, null=True, verbose_name='close time')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Shelter',
        ),
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ServiceType'),
        ),
    ]
