# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='hours_close',
            field=models.TimeField(blank=True, verbose_name='close time'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='hours_open',
            field=models.TimeField(blank=True, verbose_name='open time'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
