# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-03 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimony',
            options={'verbose_name_plural': 'testimonials'},
        ),
        migrations.AddField(
            model_name='testimony',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL),
        ),
    ]
