# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-11 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_testimony_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(upload_to='C:\\Users\\mklit\\gitProjects\\pdx-heo\\media'),
        ),
    ]
