# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170716_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
    ]
