# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-11 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170810_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimony',
            name='image',
            field=models.ImageField(upload_to='documents'),
        ),
    ]
