# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_organization_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='updated_date',
        ),
        migrations.AlterField(
            model_name='organization',
            name='hours_close',
            field=models.TimeField(verbose_name='close time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='hours_open',
            field=models.TimeField(verbose_name='open time'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
