# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170716_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='hours_close',
            field=models.TimeField(blank=True, null=True, verbose_name='close time'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='hours_open',
            field=models.TimeField(blank=True, null=True, verbose_name='open time'),
        ),
    ]
