# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdxheo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('address', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('hours_open', models.TimeField(verbose_name='open time')),
                ('hours_close', models.TimeField(verbose_name='close time')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdxheo.Organization')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
