# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 04:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdxheo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shelters',
            new_name='Shelter',
        ),
    ]
