# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdxheo', '0002_auto_20170706_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
